root = "."
tmp_dir = "tmp"

[build]
cmd = "templ generate && npx @tailwindcss/cli -i ./assets/input.css -o ./assets/output.css && go build -o ./tmp/main ./cmd/main.go"
bin = "./tmp/main"
full_bin = "./tmp/main"
include_ext = ["go", "templ"]
exclude_dir = ["assets", "tmp", "vendor", "node_modules", ".git"]
exclude_regex = [".*_templ.go", "_test.go"]
delay = 1000
stop_on_error = true
send_interrupt = true
kill_delay = 500

[log]
time = true
level = "debug"

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true
